In [4]:
import numpy as np
from sklearn.neighbors import kneighbors_graph
from scipy.sparse.csgraph import laplacian
from scipy.spatial.distance import pdist, squareform
from lund.lund import LearningbyUnsupervisedNonlinearDiffusion
from lund.utils import GraphExtractor,DensityEstimator
from model.utils import loadHSI,calculate_aligned_accuracy


data_path, gt_path, data_name, gt_name = '/Users/seoli/Desktop/DIAMONDS/Tufts2024/data/SalinasA_corrected.mat', '/Users/seoli/Desktop/DIAMONDS/Tufts2024/data/SalinasA_gt.mat', 'salinasA_corrected', 'salinasA_gt'
# data_path, gt_path, data_name, gt_name = '/Users/aryamantepal/Desktop/Tufts2024/data/SalinasA_corrected.mat', '/Users/aryamantepal/Desktop/Tufts2024/data/SalinasA_gt.mat', 'salinasA_corrected', 'salinasA_gt'


X, M, N, D, HSI, GT, Y, n, K = loadHSI(data_path, gt_path, data_name, gt_name)

GT = GT - 1
HSI = X.reshape((M, N, D))

graph_extractor = GraphExtractor(sigma=1.0, DiffusionNN=10, NEigs=5) #should probably add like sucess print statements here bc idrk if this works just yet..
density_estimator = DensityEstimator(DensityNN=10, Sigma0=1.0)

p = density_estimator.kde(X)
print(p)
G = graph_extractor.extract_graph(X)

t = 43

C, K, Dt = LearningbyUnsupervisedNonlinearDiffusion(X, t, G,p)

print("Cluster labels:", C)
print("Number of clusters:", K)
print("Diffusion distances:", Dt)

accuracy = calculate_aligned_accuracy(GT, C)
print("Aligned Accuracy:", accuracy)

#note potentially worth running in an env. i cant


d is squareformed
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.95619997e-05 2.13084291e-05 1.82676956e-05 ... 1.93605231e-05
  1.91672585e-05 2.02379871e-05]
 [2.63924017e-03 5.79243245e-03 4.87791149e-03 ... 4.32487993e-03
  3.57484627e-03 3.34426012e-03]
 ...
 [1.85234510e-01 1.86801899e-01 1.84560936e-01 ... 1.57475616e-01
  1.58740074e-01 1.56439226e-01]
 [9.21956159e-01 9.24235272e-01 9.22189827e-01 ... 8.82174243e-01
  8.81409150e-01 8.83485616e-01]
 [1.73011737e+00 1.72960421e+00 1.72983640e+00 ... 1.68604310e+00
  1.68459984e+00 1.68519407e+00]]
pre sum)
Updated
[0.00014012 0.00014012 0.00014012 ... 0.00014012 0.00014012 0.00014012]
Dist AFTER squareform: [[0.         0.00659074 0.0062464  ... 0.15397544 0.15525093 0.15317906]
 [0.00659074 0.         0.00850317 ... 0.15566479 0.15700914 0.15493949]
 [0.0062464  0.00850317 0.         ... 0.15338585 0.15468846 0.15269997]
 ...
 [0.15397544 0.15566479 0.15338585 ... 0.     

IndexError: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 7138